//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSunSet.CarRegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleInformation", Namespace="http://dmr.vestjylland.dk/schemas")]
    [System.SerializableAttribute()]
    public partial class VehicleInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnvendelseNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnvendelseNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EgenVaegtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NoSunSet.CarRegistrationService.EjerBruger[] EjerBrugereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FoersteRegistreringDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KarrosseriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KarrosseriNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoeretoejIdentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaerkeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaerkeNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NoSunSet.CarRegistrationService.VehicleInformation[] MoreVehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MotorEffektField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MotorEffektHKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistreringsNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StelNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalVaegtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeGodkendelseNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantNummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnvendelseNavn {
            get {
                return this.AnvendelseNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvendelseNavnField, value) != true)) {
                    this.AnvendelseNavnField = value;
                    this.RaisePropertyChanged("AnvendelseNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnvendelseNummer {
            get {
                return this.AnvendelseNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvendelseNummerField, value) != true)) {
                    this.AnvendelseNummerField = value;
                    this.RaisePropertyChanged("AnvendelseNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EgenVaegt {
            get {
                return this.EgenVaegtField;
            }
            set {
                if ((object.ReferenceEquals(this.EgenVaegtField, value) != true)) {
                    this.EgenVaegtField = value;
                    this.RaisePropertyChanged("EgenVaegt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NoSunSet.CarRegistrationService.EjerBruger[] EjerBrugere {
            get {
                return this.EjerBrugereField;
            }
            set {
                if ((object.ReferenceEquals(this.EjerBrugereField, value) != true)) {
                    this.EjerBrugereField = value;
                    this.RaisePropertyChanged("EjerBrugere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FoersteRegistreringDato {
            get {
                return this.FoersteRegistreringDatoField;
            }
            set {
                if ((this.FoersteRegistreringDatoField.Equals(value) != true)) {
                    this.FoersteRegistreringDatoField = value;
                    this.RaisePropertyChanged("FoersteRegistreringDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Karrosseri {
            get {
                return this.KarrosseriField;
            }
            set {
                if ((object.ReferenceEquals(this.KarrosseriField, value) != true)) {
                    this.KarrosseriField = value;
                    this.RaisePropertyChanged("Karrosseri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KarrosseriNummer {
            get {
                return this.KarrosseriNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.KarrosseriNummerField, value) != true)) {
                    this.KarrosseriNummerField = value;
                    this.RaisePropertyChanged("KarrosseriNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KoeretoejIdent {
            get {
                return this.KoeretoejIdentField;
            }
            set {
                if ((object.ReferenceEquals(this.KoeretoejIdentField, value) != true)) {
                    this.KoeretoejIdentField = value;
                    this.RaisePropertyChanged("KoeretoejIdent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maerke {
            get {
                return this.MaerkeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaerkeField, value) != true)) {
                    this.MaerkeField = value;
                    this.RaisePropertyChanged("Maerke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaerkeNummer {
            get {
                return this.MaerkeNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.MaerkeNummerField, value) != true)) {
                    this.MaerkeNummerField = value;
                    this.RaisePropertyChanged("MaerkeNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelNummer {
            get {
                return this.ModelNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNummerField, value) != true)) {
                    this.ModelNummerField = value;
                    this.RaisePropertyChanged("ModelNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NoSunSet.CarRegistrationService.VehicleInformation[] MoreVehicles {
            get {
                return this.MoreVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreVehiclesField, value) != true)) {
                    this.MoreVehiclesField = value;
                    this.RaisePropertyChanged("MoreVehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MotorEffekt {
            get {
                return this.MotorEffektField;
            }
            set {
                if ((this.MotorEffektField.Equals(value) != true)) {
                    this.MotorEffektField = value;
                    this.RaisePropertyChanged("MotorEffekt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MotorEffektHK {
            get {
                return this.MotorEffektHKField;
            }
            set {
                if ((this.MotorEffektHKField.Equals(value) != true)) {
                    this.MotorEffektHKField = value;
                    this.RaisePropertyChanged("MotorEffektHK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistreringsNummer {
            get {
                return this.RegistreringsNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistreringsNummerField, value) != true)) {
                    this.RegistreringsNummerField = value;
                    this.RaisePropertyChanged("RegistreringsNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StelNummer {
            get {
                return this.StelNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.StelNummerField, value) != true)) {
                    this.StelNummerField = value;
                    this.RaisePropertyChanged("StelNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalVaegt {
            get {
                return this.TotalVaegtField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalVaegtField, value) != true)) {
                    this.TotalVaegtField = value;
                    this.RaisePropertyChanged("TotalVaegt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeGodkendelseNummer {
            get {
                return this.TypeGodkendelseNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeGodkendelseNummerField, value) != true)) {
                    this.TypeGodkendelseNummerField = value;
                    this.RaisePropertyChanged("TypeGodkendelseNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeNummer {
            get {
                return this.TypeNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNummerField, value) != true)) {
                    this.TypeNummerField = value;
                    this.RaisePropertyChanged("TypeNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variant {
            get {
                return this.VariantField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantField, value) != true)) {
                    this.VariantField = value;
                    this.RaisePropertyChanged("Variant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VariantNummer {
            get {
                return this.VariantNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantNummerField, value) != true)) {
                    this.VariantNummerField = value;
                    this.RaisePropertyChanged("VariantNummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EjerBruger", Namespace="http://dmr.vestjylland.dk/schemas")]
    [System.SerializableAttribute()]
    public partial class EjerBruger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVR_CPRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NoSunSet.CarRegistrationService.EjerBrugerForholdType EjerBrugerForholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NoSunSet.CarRegistrationService.EjerBrugerEnhedsType EjerBrugerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HusBogstavField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HusNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDistriktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrimaerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduktionEnhedNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VejNavnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVR_CPR {
            get {
                return this.CVR_CPRField;
            }
            set {
                if ((object.ReferenceEquals(this.CVR_CPRField, value) != true)) {
                    this.CVR_CPRField = value;
                    this.RaisePropertyChanged("CVR_CPR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NoSunSet.CarRegistrationService.EjerBrugerForholdType EjerBrugerForhold {
            get {
                return this.EjerBrugerForholdField;
            }
            set {
                if ((this.EjerBrugerForholdField.Equals(value) != true)) {
                    this.EjerBrugerForholdField = value;
                    this.RaisePropertyChanged("EjerBrugerForhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NoSunSet.CarRegistrationService.EjerBrugerEnhedsType EjerBrugerType {
            get {
                return this.EjerBrugerTypeField;
            }
            set {
                if ((this.EjerBrugerTypeField.Equals(value) != true)) {
                    this.EjerBrugerTypeField = value;
                    this.RaisePropertyChanged("EjerBrugerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HusBogstav {
            get {
                return this.HusBogstavField;
            }
            set {
                if ((object.ReferenceEquals(this.HusBogstavField, value) != true)) {
                    this.HusBogstavField = value;
                    this.RaisePropertyChanged("HusBogstav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HusNummer {
            get {
                return this.HusNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.HusNummerField, value) != true)) {
                    this.HusNummerField = value;
                    this.RaisePropertyChanged("HusNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDistrikt {
            get {
                return this.PostDistriktField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDistriktField, value) != true)) {
                    this.PostDistriktField = value;
                    this.RaisePropertyChanged("PostDistrikt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostNummer {
            get {
                return this.PostNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.PostNummerField, value) != true)) {
                    this.PostNummerField = value;
                    this.RaisePropertyChanged("PostNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Primaer {
            get {
                return this.PrimaerField;
            }
            set {
                if ((this.PrimaerField.Equals(value) != true)) {
                    this.PrimaerField = value;
                    this.RaisePropertyChanged("Primaer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProduktionEnhedNummer {
            get {
                return this.ProduktionEnhedNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduktionEnhedNummerField, value) != true)) {
                    this.ProduktionEnhedNummerField = value;
                    this.RaisePropertyChanged("ProduktionEnhedNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SENummer {
            get {
                return this.SENummerField;
            }
            set {
                if ((object.ReferenceEquals(this.SENummerField, value) != true)) {
                    this.SENummerField = value;
                    this.RaisePropertyChanged("SENummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VejNavn {
            get {
                return this.VejNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.VejNavnField, value) != true)) {
                    this.VejNavnField = value;
                    this.RaisePropertyChanged("VejNavn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EjerBrugerForholdType", Namespace="http://dmr.vestjylland.dk/schemas")]
    public enum EjerBrugerForholdType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ejer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bruger = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EjerBrugerEnhedsType", Namespace="http://dmr.vestjylland.dk/schemas")]
    public enum EjerBrugerEnhedsType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ukendt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Person = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Virksomhed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UdenlandskPerson = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UdenlandskVirksomhed = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KoeretoejModelVariantRegisterRecord", Namespace="http://dmr.vestjylland.dk/schemas")]
    [System.SerializableAttribute()]
    public partial class KoeretoejModelVariantRegisterRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ModelVariantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FabrikatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FabrikatNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelserieNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short KarosseritypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KarosseritypeNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DoereAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KarosserilaengdetypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrivhjultypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ModelseriegenerationsnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ModelseriefaceliftnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AkselafstandMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SporviddeForMM_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SporviddeForMM_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SporviddeBagMM_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SporviddeBagMM_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SiddepladserAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte AirbagsAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SikkerhedsstjernerAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LaengdeMM_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LaengdeMM_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BreddeMM_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BreddeMM_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoejdeMM_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoejdeMM_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrivmiddeltypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrivmiddeltypeNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CylindreAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SlagvolumenCCMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotorstoerrelseLiterBetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaksimalEffektHKBetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaksimalEffektKWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaksimalEffektVedOMDRprMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaksimaltDrejningsmomentNMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaksimalDrejningsmomentVedOMDRprMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EUmiljoenormnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotormaerkningskoderCSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TransmissiontypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissiontypeNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short GearAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantbetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelTillaegsbetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdstyrsniveaubetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KarosseriTillaegsbetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotorTillaegsbetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionTillaegsbetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplerendeVariantbetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EgenvaegtKG_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EgenvaegtKG_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KoereklarvaegtKG_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KoereklarvaegtKG_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalvaegtKG_nedreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalvaegtKG_oevreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DrivmiddelforbrugKMprLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ELforbrugWhprKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CO2udledningGRAMprKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TophastighedKMprTIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Accelerationsevne0til100kmtSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EFtypegodkendelsesnummerCSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DKtypegodkendelsesnummerCSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRMmaerkekodeCSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DMRmaerkemodelvarianttypeIdCSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DMRmodelgruppeIdCSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AargangNysalgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StandardprisIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NyprisKRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NyprisErEstimeretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NyprisErPlusMomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NyprisMomsbeloebKRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatoOprettetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatoSenestRettetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatoDeaktiveretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ModelVariantId {
            get {
                return this.ModelVariantIdField;
            }
            set {
                if ((this.ModelVariantIdField.Equals(value) != true)) {
                    this.ModelVariantIdField = value;
                    this.RaisePropertyChanged("ModelVariantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeNavn {
            get {
                return this.TypeNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNavnField, value) != true)) {
                    this.TypeNavnField = value;
                    this.RaisePropertyChanged("TypeNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int FabrikatId {
            get {
                return this.FabrikatIdField;
            }
            set {
                if ((this.FabrikatIdField.Equals(value) != true)) {
                    this.FabrikatIdField = value;
                    this.RaisePropertyChanged("FabrikatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string FabrikatNavn {
            get {
                return this.FabrikatNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.FabrikatNavnField, value) != true)) {
                    this.FabrikatNavnField = value;
                    this.RaisePropertyChanged("FabrikatNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ModelserieNavn {
            get {
                return this.ModelserieNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelserieNavnField, value) != true)) {
                    this.ModelserieNavnField = value;
                    this.RaisePropertyChanged("ModelserieNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public short KarosseritypeId {
            get {
                return this.KarosseritypeIdField;
            }
            set {
                if ((this.KarosseritypeIdField.Equals(value) != true)) {
                    this.KarosseritypeIdField = value;
                    this.RaisePropertyChanged("KarosseritypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string KarosseritypeNavn {
            get {
                return this.KarosseritypeNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.KarosseritypeNavnField, value) != true)) {
                    this.KarosseritypeNavnField = value;
                    this.RaisePropertyChanged("KarosseritypeNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public byte DoereAntal {
            get {
                return this.DoereAntalField;
            }
            set {
                if ((this.DoereAntalField.Equals(value) != true)) {
                    this.DoereAntalField = value;
                    this.RaisePropertyChanged("DoereAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string KarosserilaengdetypeId {
            get {
                return this.KarosserilaengdetypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.KarosserilaengdetypeIdField, value) != true)) {
                    this.KarosserilaengdetypeIdField = value;
                    this.RaisePropertyChanged("KarosserilaengdetypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string DrivhjultypeId {
            get {
                return this.DrivhjultypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DrivhjultypeIdField, value) != true)) {
                    this.DrivhjultypeIdField = value;
                    this.RaisePropertyChanged("DrivhjultypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public byte Modelseriegenerationsnummer {
            get {
                return this.ModelseriegenerationsnummerField;
            }
            set {
                if ((this.ModelseriegenerationsnummerField.Equals(value) != true)) {
                    this.ModelseriegenerationsnummerField = value;
                    this.RaisePropertyChanged("Modelseriegenerationsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public byte Modelseriefaceliftnummer {
            get {
                return this.ModelseriefaceliftnummerField;
            }
            set {
                if ((this.ModelseriefaceliftnummerField.Equals(value) != true)) {
                    this.ModelseriefaceliftnummerField = value;
                    this.RaisePropertyChanged("Modelseriefaceliftnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public short AkselafstandMM {
            get {
                return this.AkselafstandMMField;
            }
            set {
                if ((this.AkselafstandMMField.Equals(value) != true)) {
                    this.AkselafstandMMField = value;
                    this.RaisePropertyChanged("AkselafstandMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public short SporviddeForMM_nedre {
            get {
                return this.SporviddeForMM_nedreField;
            }
            set {
                if ((this.SporviddeForMM_nedreField.Equals(value) != true)) {
                    this.SporviddeForMM_nedreField = value;
                    this.RaisePropertyChanged("SporviddeForMM_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public short SporviddeForMM_oevre {
            get {
                return this.SporviddeForMM_oevreField;
            }
            set {
                if ((this.SporviddeForMM_oevreField.Equals(value) != true)) {
                    this.SporviddeForMM_oevreField = value;
                    this.RaisePropertyChanged("SporviddeForMM_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public short SporviddeBagMM_nedre {
            get {
                return this.SporviddeBagMM_nedreField;
            }
            set {
                if ((this.SporviddeBagMM_nedreField.Equals(value) != true)) {
                    this.SporviddeBagMM_nedreField = value;
                    this.RaisePropertyChanged("SporviddeBagMM_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public short SporviddeBagMM_oevre {
            get {
                return this.SporviddeBagMM_oevreField;
            }
            set {
                if ((this.SporviddeBagMM_oevreField.Equals(value) != true)) {
                    this.SporviddeBagMM_oevreField = value;
                    this.RaisePropertyChanged("SporviddeBagMM_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public byte SiddepladserAntal {
            get {
                return this.SiddepladserAntalField;
            }
            set {
                if ((this.SiddepladserAntalField.Equals(value) != true)) {
                    this.SiddepladserAntalField = value;
                    this.RaisePropertyChanged("SiddepladserAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public byte AirbagsAntal {
            get {
                return this.AirbagsAntalField;
            }
            set {
                if ((this.AirbagsAntalField.Equals(value) != true)) {
                    this.AirbagsAntalField = value;
                    this.RaisePropertyChanged("AirbagsAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public byte SikkerhedsstjernerAntal {
            get {
                return this.SikkerhedsstjernerAntalField;
            }
            set {
                if ((this.SikkerhedsstjernerAntalField.Equals(value) != true)) {
                    this.SikkerhedsstjernerAntalField = value;
                    this.RaisePropertyChanged("SikkerhedsstjernerAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public int LaengdeMM_nedre {
            get {
                return this.LaengdeMM_nedreField;
            }
            set {
                if ((this.LaengdeMM_nedreField.Equals(value) != true)) {
                    this.LaengdeMM_nedreField = value;
                    this.RaisePropertyChanged("LaengdeMM_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int LaengdeMM_oevre {
            get {
                return this.LaengdeMM_oevreField;
            }
            set {
                if ((this.LaengdeMM_oevreField.Equals(value) != true)) {
                    this.LaengdeMM_oevreField = value;
                    this.RaisePropertyChanged("LaengdeMM_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int BreddeMM_nedre {
            get {
                return this.BreddeMM_nedreField;
            }
            set {
                if ((this.BreddeMM_nedreField.Equals(value) != true)) {
                    this.BreddeMM_nedreField = value;
                    this.RaisePropertyChanged("BreddeMM_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public int BreddeMM_oevre {
            get {
                return this.BreddeMM_oevreField;
            }
            set {
                if ((this.BreddeMM_oevreField.Equals(value) != true)) {
                    this.BreddeMM_oevreField = value;
                    this.RaisePropertyChanged("BreddeMM_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public int HoejdeMM_nedre {
            get {
                return this.HoejdeMM_nedreField;
            }
            set {
                if ((this.HoejdeMM_nedreField.Equals(value) != true)) {
                    this.HoejdeMM_nedreField = value;
                    this.RaisePropertyChanged("HoejdeMM_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public int HoejdeMM_oevre {
            get {
                return this.HoejdeMM_oevreField;
            }
            set {
                if ((this.HoejdeMM_oevreField.Equals(value) != true)) {
                    this.HoejdeMM_oevreField = value;
                    this.RaisePropertyChanged("HoejdeMM_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string DrivmiddeltypeId {
            get {
                return this.DrivmiddeltypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DrivmiddeltypeIdField, value) != true)) {
                    this.DrivmiddeltypeIdField = value;
                    this.RaisePropertyChanged("DrivmiddeltypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string DrivmiddeltypeNavn {
            get {
                return this.DrivmiddeltypeNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.DrivmiddeltypeNavnField, value) != true)) {
                    this.DrivmiddeltypeNavnField = value;
                    this.RaisePropertyChanged("DrivmiddeltypeNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public byte CylindreAntal {
            get {
                return this.CylindreAntalField;
            }
            set {
                if ((this.CylindreAntalField.Equals(value) != true)) {
                    this.CylindreAntalField = value;
                    this.RaisePropertyChanged("CylindreAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public int SlagvolumenCCM {
            get {
                return this.SlagvolumenCCMField;
            }
            set {
                if ((this.SlagvolumenCCMField.Equals(value) != true)) {
                    this.SlagvolumenCCMField = value;
                    this.RaisePropertyChanged("SlagvolumenCCM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string MotorstoerrelseLiterBetegnelse {
            get {
                return this.MotorstoerrelseLiterBetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorstoerrelseLiterBetegnelseField, value) != true)) {
                    this.MotorstoerrelseLiterBetegnelseField = value;
                    this.RaisePropertyChanged("MotorstoerrelseLiterBetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public int MaksimalEffektHKBetegnelse {
            get {
                return this.MaksimalEffektHKBetegnelseField;
            }
            set {
                if ((this.MaksimalEffektHKBetegnelseField.Equals(value) != true)) {
                    this.MaksimalEffektHKBetegnelseField = value;
                    this.RaisePropertyChanged("MaksimalEffektHKBetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public int MaksimalEffektKW {
            get {
                return this.MaksimalEffektKWField;
            }
            set {
                if ((this.MaksimalEffektKWField.Equals(value) != true)) {
                    this.MaksimalEffektKWField = value;
                    this.RaisePropertyChanged("MaksimalEffektKW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public int MaksimalEffektVedOMDRprMin {
            get {
                return this.MaksimalEffektVedOMDRprMinField;
            }
            set {
                if ((this.MaksimalEffektVedOMDRprMinField.Equals(value) != true)) {
                    this.MaksimalEffektVedOMDRprMinField = value;
                    this.RaisePropertyChanged("MaksimalEffektVedOMDRprMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public int MaksimaltDrejningsmomentNM {
            get {
                return this.MaksimaltDrejningsmomentNMField;
            }
            set {
                if ((this.MaksimaltDrejningsmomentNMField.Equals(value) != true)) {
                    this.MaksimaltDrejningsmomentNMField = value;
                    this.RaisePropertyChanged("MaksimaltDrejningsmomentNM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public int MaksimalDrejningsmomentVedOMDRprMin {
            get {
                return this.MaksimalDrejningsmomentVedOMDRprMinField;
            }
            set {
                if ((this.MaksimalDrejningsmomentVedOMDRprMinField.Equals(value) != true)) {
                    this.MaksimalDrejningsmomentVedOMDRprMinField = value;
                    this.RaisePropertyChanged("MaksimalDrejningsmomentVedOMDRprMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public byte EUmiljoenormnummer {
            get {
                return this.EUmiljoenormnummerField;
            }
            set {
                if ((this.EUmiljoenormnummerField.Equals(value) != true)) {
                    this.EUmiljoenormnummerField = value;
                    this.RaisePropertyChanged("EUmiljoenormnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public string MotormaerkningskoderCSV {
            get {
                return this.MotormaerkningskoderCSVField;
            }
            set {
                if ((object.ReferenceEquals(this.MotormaerkningskoderCSVField, value) != true)) {
                    this.MotormaerkningskoderCSVField = value;
                    this.RaisePropertyChanged("MotormaerkningskoderCSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public short TransmissiontypeId {
            get {
                return this.TransmissiontypeIdField;
            }
            set {
                if ((this.TransmissiontypeIdField.Equals(value) != true)) {
                    this.TransmissiontypeIdField = value;
                    this.RaisePropertyChanged("TransmissiontypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string TransmissiontypeNavn {
            get {
                return this.TransmissiontypeNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissiontypeNavnField, value) != true)) {
                    this.TransmissiontypeNavnField = value;
                    this.RaisePropertyChanged("TransmissiontypeNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public short GearAntal {
            get {
                return this.GearAntalField;
            }
            set {
                if ((this.GearAntalField.Equals(value) != true)) {
                    this.GearAntalField = value;
                    this.RaisePropertyChanged("GearAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public int ModelId {
            get {
                return this.ModelIdField;
            }
            set {
                if ((this.ModelIdField.Equals(value) != true)) {
                    this.ModelIdField = value;
                    this.RaisePropertyChanged("ModelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public string ModelNavn {
            get {
                return this.ModelNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNavnField, value) != true)) {
                    this.ModelNavnField = value;
                    this.RaisePropertyChanged("ModelNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public string Variantbetegnelse {
            get {
                return this.VariantbetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantbetegnelseField, value) != true)) {
                    this.VariantbetegnelseField = value;
                    this.RaisePropertyChanged("Variantbetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public string ModelTillaegsbetegnelse {
            get {
                return this.ModelTillaegsbetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelTillaegsbetegnelseField, value) != true)) {
                    this.ModelTillaegsbetegnelseField = value;
                    this.RaisePropertyChanged("ModelTillaegsbetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public string Udstyrsniveaubetegnelse {
            get {
                return this.UdstyrsniveaubetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.UdstyrsniveaubetegnelseField, value) != true)) {
                    this.UdstyrsniveaubetegnelseField = value;
                    this.RaisePropertyChanged("Udstyrsniveaubetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public string KarosseriTillaegsbetegnelse {
            get {
                return this.KarosseriTillaegsbetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.KarosseriTillaegsbetegnelseField, value) != true)) {
                    this.KarosseriTillaegsbetegnelseField = value;
                    this.RaisePropertyChanged("KarosseriTillaegsbetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public string MotorTillaegsbetegnelse {
            get {
                return this.MotorTillaegsbetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorTillaegsbetegnelseField, value) != true)) {
                    this.MotorTillaegsbetegnelseField = value;
                    this.RaisePropertyChanged("MotorTillaegsbetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public string TransmissionTillaegsbetegnelse {
            get {
                return this.TransmissionTillaegsbetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionTillaegsbetegnelseField, value) != true)) {
                    this.TransmissionTillaegsbetegnelseField = value;
                    this.RaisePropertyChanged("TransmissionTillaegsbetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public string SupplerendeVariantbetegnelse {
            get {
                return this.SupplerendeVariantbetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplerendeVariantbetegnelseField, value) != true)) {
                    this.SupplerendeVariantbetegnelseField = value;
                    this.RaisePropertyChanged("SupplerendeVariantbetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=51)]
        public int EgenvaegtKG_nedre {
            get {
                return this.EgenvaegtKG_nedreField;
            }
            set {
                if ((this.EgenvaegtKG_nedreField.Equals(value) != true)) {
                    this.EgenvaegtKG_nedreField = value;
                    this.RaisePropertyChanged("EgenvaegtKG_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=52)]
        public int EgenvaegtKG_oevre {
            get {
                return this.EgenvaegtKG_oevreField;
            }
            set {
                if ((this.EgenvaegtKG_oevreField.Equals(value) != true)) {
                    this.EgenvaegtKG_oevreField = value;
                    this.RaisePropertyChanged("EgenvaegtKG_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=53)]
        public int KoereklarvaegtKG_nedre {
            get {
                return this.KoereklarvaegtKG_nedreField;
            }
            set {
                if ((this.KoereklarvaegtKG_nedreField.Equals(value) != true)) {
                    this.KoereklarvaegtKG_nedreField = value;
                    this.RaisePropertyChanged("KoereklarvaegtKG_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=54)]
        public int KoereklarvaegtKG_oevre {
            get {
                return this.KoereklarvaegtKG_oevreField;
            }
            set {
                if ((this.KoereklarvaegtKG_oevreField.Equals(value) != true)) {
                    this.KoereklarvaegtKG_oevreField = value;
                    this.RaisePropertyChanged("KoereklarvaegtKG_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=55)]
        public int TotalvaegtKG_nedre {
            get {
                return this.TotalvaegtKG_nedreField;
            }
            set {
                if ((this.TotalvaegtKG_nedreField.Equals(value) != true)) {
                    this.TotalvaegtKG_nedreField = value;
                    this.RaisePropertyChanged("TotalvaegtKG_nedre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=56)]
        public int TotalvaegtKG_oevre {
            get {
                return this.TotalvaegtKG_oevreField;
            }
            set {
                if ((this.TotalvaegtKG_oevreField.Equals(value) != true)) {
                    this.TotalvaegtKG_oevreField = value;
                    this.RaisePropertyChanged("TotalvaegtKG_oevre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=57)]
        public string ESP {
            get {
                return this.ESPField;
            }
            set {
                if ((object.ReferenceEquals(this.ESPField, value) != true)) {
                    this.ESPField = value;
                    this.RaisePropertyChanged("ESP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=58)]
        public string ABS {
            get {
                return this.ABSField;
            }
            set {
                if ((object.ReferenceEquals(this.ABSField, value) != true)) {
                    this.ABSField = value;
                    this.RaisePropertyChanged("ABS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=59)]
        public string DPF {
            get {
                return this.DPFField;
            }
            set {
                if ((object.ReferenceEquals(this.DPFField, value) != true)) {
                    this.DPFField = value;
                    this.RaisePropertyChanged("DPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=60)]
        public float DrivmiddelforbrugKMprL {
            get {
                return this.DrivmiddelforbrugKMprLField;
            }
            set {
                if ((this.DrivmiddelforbrugKMprLField.Equals(value) != true)) {
                    this.DrivmiddelforbrugKMprLField = value;
                    this.RaisePropertyChanged("DrivmiddelforbrugKMprL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=61)]
        public int ELforbrugWhprKM {
            get {
                return this.ELforbrugWhprKMField;
            }
            set {
                if ((this.ELforbrugWhprKMField.Equals(value) != true)) {
                    this.ELforbrugWhprKMField = value;
                    this.RaisePropertyChanged("ELforbrugWhprKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=62)]
        public float CO2udledningGRAMprKM {
            get {
                return this.CO2udledningGRAMprKMField;
            }
            set {
                if ((this.CO2udledningGRAMprKMField.Equals(value) != true)) {
                    this.CO2udledningGRAMprKMField = value;
                    this.RaisePropertyChanged("CO2udledningGRAMprKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=63)]
        public short TophastighedKMprTIME {
            get {
                return this.TophastighedKMprTIMEField;
            }
            set {
                if ((this.TophastighedKMprTIMEField.Equals(value) != true)) {
                    this.TophastighedKMprTIMEField = value;
                    this.RaisePropertyChanged("TophastighedKMprTIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=64)]
        public float Accelerationsevne0til100kmtS {
            get {
                return this.Accelerationsevne0til100kmtSField;
            }
            set {
                if ((this.Accelerationsevne0til100kmtSField.Equals(value) != true)) {
                    this.Accelerationsevne0til100kmtSField = value;
                    this.RaisePropertyChanged("Accelerationsevne0til100kmtS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=65)]
        public string EFtypegodkendelsesnummerCSV {
            get {
                return this.EFtypegodkendelsesnummerCSVField;
            }
            set {
                if ((object.ReferenceEquals(this.EFtypegodkendelsesnummerCSVField, value) != true)) {
                    this.EFtypegodkendelsesnummerCSVField = value;
                    this.RaisePropertyChanged("EFtypegodkendelsesnummerCSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=66)]
        public string DKtypegodkendelsesnummerCSV {
            get {
                return this.DKtypegodkendelsesnummerCSVField;
            }
            set {
                if ((object.ReferenceEquals(this.DKtypegodkendelsesnummerCSVField, value) != true)) {
                    this.DKtypegodkendelsesnummerCSVField = value;
                    this.RaisePropertyChanged("DKtypegodkendelsesnummerCSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=67)]
        public string CRMmaerkekodeCSV {
            get {
                return this.CRMmaerkekodeCSVField;
            }
            set {
                if ((object.ReferenceEquals(this.CRMmaerkekodeCSVField, value) != true)) {
                    this.CRMmaerkekodeCSVField = value;
                    this.RaisePropertyChanged("CRMmaerkekodeCSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=68)]
        public string DMRmaerkemodelvarianttypeIdCSV {
            get {
                return this.DMRmaerkemodelvarianttypeIdCSVField;
            }
            set {
                if ((object.ReferenceEquals(this.DMRmaerkemodelvarianttypeIdCSVField, value) != true)) {
                    this.DMRmaerkemodelvarianttypeIdCSVField = value;
                    this.RaisePropertyChanged("DMRmaerkemodelvarianttypeIdCSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=69)]
        public string DMRmodelgruppeIdCSV {
            get {
                return this.DMRmodelgruppeIdCSVField;
            }
            set {
                if ((object.ReferenceEquals(this.DMRmodelgruppeIdCSVField, value) != true)) {
                    this.DMRmodelgruppeIdCSVField = value;
                    this.RaisePropertyChanged("DMRmodelgruppeIdCSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=70)]
        public short AargangNysalg {
            get {
                return this.AargangNysalgField;
            }
            set {
                if ((this.AargangNysalgField.Equals(value) != true)) {
                    this.AargangNysalgField = value;
                    this.RaisePropertyChanged("AargangNysalg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=71)]
        public int StandardprisId {
            get {
                return this.StandardprisIdField;
            }
            set {
                if ((this.StandardprisIdField.Equals(value) != true)) {
                    this.StandardprisIdField = value;
                    this.RaisePropertyChanged("StandardprisId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=72)]
        public int NyprisKR {
            get {
                return this.NyprisKRField;
            }
            set {
                if ((this.NyprisKRField.Equals(value) != true)) {
                    this.NyprisKRField = value;
                    this.RaisePropertyChanged("NyprisKR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=73)]
        public bool NyprisErEstimeret {
            get {
                return this.NyprisErEstimeretField;
            }
            set {
                if ((this.NyprisErEstimeretField.Equals(value) != true)) {
                    this.NyprisErEstimeretField = value;
                    this.RaisePropertyChanged("NyprisErEstimeret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=74)]
        public bool NyprisErPlusMoms {
            get {
                return this.NyprisErPlusMomsField;
            }
            set {
                if ((this.NyprisErPlusMomsField.Equals(value) != true)) {
                    this.NyprisErPlusMomsField = value;
                    this.RaisePropertyChanged("NyprisErPlusMoms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=75)]
        public int NyprisMomsbeloebKR {
            get {
                return this.NyprisMomsbeloebKRField;
            }
            set {
                if ((this.NyprisMomsbeloebKRField.Equals(value) != true)) {
                    this.NyprisMomsbeloebKRField = value;
                    this.RaisePropertyChanged("NyprisMomsbeloebKR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=76)]
        public System.DateTime DatoOprettet {
            get {
                return this.DatoOprettetField;
            }
            set {
                if ((this.DatoOprettetField.Equals(value) != true)) {
                    this.DatoOprettetField = value;
                    this.RaisePropertyChanged("DatoOprettet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=77)]
        public System.DateTime DatoSenestRettet {
            get {
                return this.DatoSenestRettetField;
            }
            set {
                if ((this.DatoSenestRettetField.Equals(value) != true)) {
                    this.DatoSenestRettetField = value;
                    this.RaisePropertyChanged("DatoSenestRettet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=78)]
        public System.DateTime DatoDeaktiveret {
            get {
                return this.DatoDeaktiveretField;
            }
            set {
                if ((this.DatoDeaktiveretField.Equals(value) != true)) {
                    this.DatoDeaktiveretField = value;
                    this.RaisePropertyChanged("DatoDeaktiveret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KIdModelVariantIdRecord", Namespace="http://dmr.vestjylland.dk/schemas")]
    [System.SerializableAttribute()]
    public partial class KIdModelVariantIdRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatoDeaktiveretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatoOprettetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DMRkoeretoejIdentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ModelVariantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatoDeaktiveret {
            get {
                return this.DatoDeaktiveretField;
            }
            set {
                if ((this.DatoDeaktiveretField.Equals(value) != true)) {
                    this.DatoDeaktiveretField = value;
                    this.RaisePropertyChanged("DatoDeaktiveret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatoOprettet {
            get {
                return this.DatoOprettetField;
            }
            set {
                if ((this.DatoOprettetField.Equals(value) != true)) {
                    this.DatoOprettetField = value;
                    this.RaisePropertyChanged("DatoOprettet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string DMRkoeretoejIdent {
            get {
                return this.DMRkoeretoejIdentField;
            }
            set {
                if ((object.ReferenceEquals(this.DMRkoeretoejIdentField, value) != true)) {
                    this.DMRkoeretoejIdentField = value;
                    this.RaisePropertyChanged("DMRkoeretoejIdent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long ModelVariantId {
            get {
                return this.ModelVariantIdField;
            }
            set {
                if ((this.ModelVariantIdField.Equals(value) != true)) {
                    this.ModelVariantIdField = value;
                    this.RaisePropertyChanged("ModelVariantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Q {
            get {
                return this.QField;
            }
            set {
                if ((this.QField.Equals(value) != true)) {
                    this.QField = value;
                    this.RaisePropertyChanged("Q");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dmr.vestjylland.dk/services", ConfigurationName="CarRegistrationService.IDmrService")]
    public interface IDmrService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByReg", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByRegResponse" +
            "")]
        NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByReg(string registreringsNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByReg", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByRegResponse" +
            "")]
        System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByRegAsync(string registreringsNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStel", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStelRespons" +
            "e")]
        NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByStel(string stelNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStel", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStelRespons" +
            "e")]
        System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByStelAsync(string stelNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByReg_NoReg", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByReg_NoRegRe" +
            "sponse")]
        NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByReg_NoReg(string registreringsNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByReg_NoReg", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByReg_NoRegRe" +
            "sponse")]
        System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByReg_NoRegAsync(string registreringsNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStel_NoReg", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStel_NoRegR" +
            "esponse")]
        NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByStel_NoReg(string stelNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStel_NoReg", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetVehicleInformationByStel_NoRegR" +
            "esponse")]
        System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByStel_NoRegAsync(string stelNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetKoeretoejModelVariantRegisterRe" +
            "cord_AutoIT", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetKoeretoejModelVariantRegisterRe" +
            "cord_AutoITResponse")]
        NoSunSet.CarRegistrationService.KoeretoejModelVariantRegisterRecord[] GetKoeretoejModelVariantRegisterRecord_AutoIT(System.DateTime datoSenestRettet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetKoeretoejModelVariantRegisterRe" +
            "cord_AutoIT", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetKoeretoejModelVariantRegisterRe" +
            "cord_AutoITResponse")]
        System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.KoeretoejModelVariantRegisterRecord[]> GetKoeretoejModelVariantRegisterRecord_AutoITAsync(System.DateTime datoSenestRettet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetKIdModelVariantIdRecord_AutoIT", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetKIdModelVariantIdRecord_AutoITR" +
            "esponse")]
        NoSunSet.CarRegistrationService.KIdModelVariantIdRecord[] GetKIdModelVariantIdRecord_AutoIT(System.DateTime datoSenestRettet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dmr.vestjylland.dk/services/IDmrService/GetKIdModelVariantIdRecord_AutoIT", ReplyAction="http://dmr.vestjylland.dk/services/IDmrService/GetKIdModelVariantIdRecord_AutoITR" +
            "esponse")]
        System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.KIdModelVariantIdRecord[]> GetKIdModelVariantIdRecord_AutoITAsync(System.DateTime datoSenestRettet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDmrServiceChannel : NoSunSet.CarRegistrationService.IDmrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DmrServiceClient : System.ServiceModel.ClientBase<NoSunSet.CarRegistrationService.IDmrService>, NoSunSet.CarRegistrationService.IDmrService {
        
        public DmrServiceClient() {
        }
        
        public DmrServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DmrServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByReg(string registreringsNummer) {
            return base.Channel.GetVehicleInformationByReg(registreringsNummer);
        }
        
        public System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByRegAsync(string registreringsNummer) {
            return base.Channel.GetVehicleInformationByRegAsync(registreringsNummer);
        }
        
        public NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByStel(string stelNummer) {
            return base.Channel.GetVehicleInformationByStel(stelNummer);
        }
        
        public System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByStelAsync(string stelNummer) {
            return base.Channel.GetVehicleInformationByStelAsync(stelNummer);
        }
        
        public NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByReg_NoReg(string registreringsNummer) {
            return base.Channel.GetVehicleInformationByReg_NoReg(registreringsNummer);
        }
        
        public System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByReg_NoRegAsync(string registreringsNummer) {
            return base.Channel.GetVehicleInformationByReg_NoRegAsync(registreringsNummer);
        }
        
        public NoSunSet.CarRegistrationService.VehicleInformation GetVehicleInformationByStel_NoReg(string stelNummer) {
            return base.Channel.GetVehicleInformationByStel_NoReg(stelNummer);
        }
        
        public System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.VehicleInformation> GetVehicleInformationByStel_NoRegAsync(string stelNummer) {
            return base.Channel.GetVehicleInformationByStel_NoRegAsync(stelNummer);
        }
        
        public NoSunSet.CarRegistrationService.KoeretoejModelVariantRegisterRecord[] GetKoeretoejModelVariantRegisterRecord_AutoIT(System.DateTime datoSenestRettet) {
            return base.Channel.GetKoeretoejModelVariantRegisterRecord_AutoIT(datoSenestRettet);
        }
        
        public System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.KoeretoejModelVariantRegisterRecord[]> GetKoeretoejModelVariantRegisterRecord_AutoITAsync(System.DateTime datoSenestRettet) {
            return base.Channel.GetKoeretoejModelVariantRegisterRecord_AutoITAsync(datoSenestRettet);
        }
        
        public NoSunSet.CarRegistrationService.KIdModelVariantIdRecord[] GetKIdModelVariantIdRecord_AutoIT(System.DateTime datoSenestRettet) {
            return base.Channel.GetKIdModelVariantIdRecord_AutoIT(datoSenestRettet);
        }
        
        public System.Threading.Tasks.Task<NoSunSet.CarRegistrationService.KIdModelVariantIdRecord[]> GetKIdModelVariantIdRecord_AutoITAsync(System.DateTime datoSenestRettet) {
            return base.Channel.GetKIdModelVariantIdRecord_AutoITAsync(datoSenestRettet);
        }
    }
}
